# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8d0f241ed6fd26d05e9fc936f61953cabfa47f01ec6dd7c08094b59cbcec7dbf80d2d60e6e91e4aa7f4f37e963212422cced04c52f78ddba4ea102c57463f12

test:
  secret_key_base: aa2893337dae5eeb3bd6d68ce3fd19e034ea5a8d0505b742a77dc36335dede424cc069d04b20a9b63405281fdcc838fa23d69bdac75163e63770a274285b7625

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
